{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.sankaran.saran",
    "module": "samplelibray",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "samplelibray-0.0.1.aar",
          "url": "samplelibray-0.0.1.aar",
          "size": 33180,
          "sha512": "418d44e6f0eb7e6304b721c3c0a7dd0a976ced31f31ff68071d3b385729b23d03525fb5d9eea68b1aa47f5ac6bedc459438dc1b1f07c989f305e407a97874335",
          "sha256": "af6d54a12b795500ce3e2684352d7f2d627717cfd66b4fec4e6b2f0027d14ddf",
          "sha1": "39c61d85b12655a7fa97fa1f8677347814db7f33",
          "md5": "ed8c46f4fc1aca6f97c5a8f1178557d0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "samplelibray-0.0.1.aar",
          "url": "samplelibray-0.0.1.aar",
          "size": 33180,
          "sha512": "418d44e6f0eb7e6304b721c3c0a7dd0a976ced31f31ff68071d3b385729b23d03525fb5d9eea68b1aa47f5ac6bedc459438dc1b1f07c989f305e407a97874335",
          "sha256": "af6d54a12b795500ce3e2684352d7f2d627717cfd66b4fec4e6b2f0027d14ddf",
          "sha1": "39c61d85b12655a7fa97fa1f8677347814db7f33",
          "md5": "ed8c46f4fc1aca6f97c5a8f1178557d0"
        }
      ]
    }
  ]
}
