{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.sankaran.saran",
    "module": "samplelibrary",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "samplelibrary-0.0.1.jar",
          "url": "samplelibrary-0.0.1.jar",
          "size": 1454,
          "sha512": "9e2a13fcdb25864f82f4c1f864ae0f0f2a870e781703be3e9661f55b4482edd253f1fd9cb3bb743d85aed3e84f4ab6dc2428069708db55ae7de3c4c16276bfee",
          "sha256": "98cc3c0723aa60b91ba642bef7475e3533af6ac6f563315e480854c739b92ac8",
          "sha1": "64cb68b69ccdf951c4c57a79b9a242092513db60",
          "md5": "34cbd57d34158798ad43ba3f71a4d4ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "samplelibrary-0.0.1.jar",
          "url": "samplelibrary-0.0.1.jar",
          "size": 1454,
          "sha512": "9e2a13fcdb25864f82f4c1f864ae0f0f2a870e781703be3e9661f55b4482edd253f1fd9cb3bb743d85aed3e84f4ab6dc2428069708db55ae7de3c4c16276bfee",
          "sha256": "98cc3c0723aa60b91ba642bef7475e3533af6ac6f563315e480854c739b92ac8",
          "sha1": "64cb68b69ccdf951c4c57a79b9a242092513db60",
          "md5": "34cbd57d34158798ad43ba3f71a4d4ed"
        }
      ]
    }
  ]
}
