{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.sankaran.saran",
    "module": "samplelibrary",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "samplelibrary-0.0.1.jar",
          "url": "samplelibrary-0.0.1.jar",
          "size": 1454,
          "sha512": "349886d40dd9721973503626d8030c86bddc26e9ce51345d0054e1cbf125621dfc85e5e4db77ee2de8f9dab66c9a51cce1629c0598d23e802f0e79eb618db9b5",
          "sha256": "4e1b1f3cda4db450f44366a1d6de337ca3608dcce72a416306f3e5c885419403",
          "sha1": "a3c4cdf659a46182dc67355f001f2644e6b669be",
          "md5": "2048f282300ce3a8aa6d271e765e154d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "samplelibrary-0.0.1.jar",
          "url": "samplelibrary-0.0.1.jar",
          "size": 1454,
          "sha512": "349886d40dd9721973503626d8030c86bddc26e9ce51345d0054e1cbf125621dfc85e5e4db77ee2de8f9dab66c9a51cce1629c0598d23e802f0e79eb618db9b5",
          "sha256": "4e1b1f3cda4db450f44366a1d6de337ca3608dcce72a416306f3e5c885419403",
          "sha1": "a3c4cdf659a46182dc67355f001f2644e6b669be",
          "md5": "2048f282300ce3a8aa6d271e765e154d"
        }
      ]
    }
  ]
}
