name: publish_to_local_maven
on:
  push:
    branches:
      - master

jobs:
  publish-to-local-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
