name: Pull and build
on:
  repository_dispatch:
    types: [ testing ]

jobs:
  publish-to-local-maven:
    name: Pull and build
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"